FROM ubuntu:18.04

LABEL maintainer=lee

RUN apt update -y

RUN apt install git -y
RUN apt install iproute2 -y
RUN apt install iptables -y
RUN apt install iputils-ping -y
RUN apt install isc-dhcp-client -y
RUN apt install isc-dhcp-server -y
RUN apt install mininet -y
RUN apt install net-tools -y
RUN apt install sudo -y
RUN apt install tcpdump -y
RUN apt install vim -y